version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network


  trade-receiver-service:
    build:
      context: .
      dockerfile: ./trade_receiver/DockerFile
    #command: nodemon --exec "python" main.py
    environment:
      FLASK_ENV: development
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    tty: true
    restart: on-failure:5
    ports:
      - "5000:5000"
    volumes:
      - ./trade_receiver:/trade_receiver
    networks:
      - network


  market-data-service:
    build:
      context: .
      dockerfile: ./market_data/Dockerfile
    #command: nodemon --exec "python" main.py
    environment:
      - IEX_TOKEN=Tpk_36614967265944c6b4b3e47be6b2b3ca
      - IEX_API_VERSION=iexcloud-sandbox
      - AMQP_URL='amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    tty: true
    depends_on:
      - rabbitmq
    restart: on-failure:5
    volumes:
      - ./market_data:/market_data
    networks:
      - network

  risk-publisher-service:
    build:
      context: .
      dockerfile: ./risk_publisher/DockerFile
    environment:
      - AMQP_URL='amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    tty: true
    depends_on:
      - rabbitmq
      - market-data-service
    restart: on-failure:5
    volumes:
      - ./risk_publisher:/risk_publisher
    networks:
      - network

networks:
  network: {}
